### ISSUE TITLE
Needs more filter.

### ISSUE THREAD

**Issue by hungarian-notation** [Ugotsta/waterpaper-ui#1]
The filter thoroughly obscured my file tree pane. but it was possible to zoom in on my code enough to be able to edit it still. This seems to go against the spirit of this ui-theme. Perhaps the effect can be increased as the zoom level or font size of the editor increases?

**Comment by R3V1Z3** [comment]
Thanks for your feedback. I'm inclined to agree. The filter is greatly affected by CSS text and box shadows so something like the following goes a long way:

```css
atom-workspace atom-text-editor {
	text-shadow:
		0 0 8px currentColor,
		0 0 12px currentColor,
		0 0 2px black;
}
```

Before the added text-shadow:
![before](https://user-images.githubusercontent.com/532645/46385864-19220a00-c673-11e8-9c94-62c36d29e6c5.png)

After:
![after](https://user-images.githubusercontent.com/532645/46385869-1cb59100-c673-11e8-86b0-0b806e556d24.png)

You can potentially add the above CSS to your Atom stylesheet ( <kbd>CTRL</kbd> - <kbd>,</kbd> 🠮 Open Config Folder 🠮  styles.css).

Does that seem adequate?
